### PR TITLE
Adding current temprature feature

### LINKED ISSUE #6: Adding current temperature
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

When ever user open the application the program will display the current temp. , humidity, wind speed in console.
User first need to add there location in one text file (only one time process) so program can read that file and fetch the current temp.

Notes: 

- Currently im using free account of API: so API request is limited to 1000 per month (ig it is fine for contribution period)

- User need to install this two library

```
#include <curl/curl.h>
#include <nlohmann/json.hpp>
```

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Volcano-Dragon**
# Fixes Issue🛠️

Closes #6 and #8 

# Description👨‍💻 

1. Fixing typos and errors
2. The program will read the user's city location from the configuration file (cnf.txt) and make an API request for current weather condition of the city

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I tested this program on my computer, and it is working fine on VS2022, before running it. The user needs to install the required libraries
```
#include <curl/curl.h>
#include <nlohmann/json.hpp>
```

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

greet_dalh_temp
greet_dalh_temp_mor
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Do provide the easy steps in the readme to install the libraries for the user understanding @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> Do provide the easy steps in the readme to install the libraries for the user understanding, @Volcano-Dragon

yes actually, i thought if this PR merged successfully, then i will create a new PR to update all the instruction and screenshots

**Comment by Rakesh9100** [comment]
Okay fine @Volcano-Dragon

**Comment by Rakesh9100** [comment]
Okay fine @Volcano-Dragon 
Looks good! Merged!!

**Comment by Rakesh9100** [comment]
Okay fine @Volcano-Dragon 
Looks good! Merged!! 🎉

**Comment by Rakesh9100** [comment]
give @Volcano-Dragon 150 points

**Pull request merged**
