### PR TITLE
Readme Updation for Temperature feature

### LINKED ISSUE #10: Updating the readme file for new features
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Updating the readme file for the new current temp feature

Adding new section for installing the required libraries and updating all other minor details

The basic structure of the Readme file will be maintained.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Volcano-Dragon**
# Fixes Issue🛠️

Closes #10

# Description👨‍💻 

I changed the readme file of the project for the new featured section and added two new sections.
1- For installation of required library
2- For how to edit the text files

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Don't edit the Overview⭐ section @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> Don't edit the Overview⭐ section @Volcano-Dragon

No need to update the screenshots?

**Comment by Rakesh9100** [comment]
It's already updated, you can check the Readme @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> It's already updated, you can check the Readme @Volcano-Dragon

But no details of tempreture (wheater) are mentioned.

**Comment by Rakesh9100** [comment]
The screenshots URL which you have updated is showing error on opening @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> The screenshots URL which you have updated is showing error on opening @Volcano-Dragon

please re-check or refresh it is opening fine in my repo

image

**Comment by Rakesh9100** [comment]
Merged!! @Volcano-Dragon 🎉

**Comment by Rakesh9100** [comment]
give @Volcano-Dragon 75 points

**Pull request merged**
